const REQUEST_BUILD_INFO = 'REQUEST_BUILD_INFO'
const RECEIVE_BUILD_INFO = 'RECEIVE_BUILD_INFO'
const REQUEST_LOGGED_USER = 'REQUEST_LOGGED_USER'
const RECEIVE_LOGGED_USER = 'RECEIVE_LOGGED_USER'
const REQUEST_COMPONENTS = 'REQUEST_COMPONENTS'
const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS'
const REQUEST_VERSIONS = 'REQUEST_VERSIONS'
const RECEIVE_VERSIONS = 'RECEIVE_VERSIONS'
const CLOSE_VERSION = 'CLOSE_VERSION'
const RECEIVE_VERSIONS_ERROR = 'RECEIVE_VERSIONS_ERROR'
const REQUEST_DEPENDENCIES = 'REQUEST_DEPENDENCIES'
const RECEIVE_DEPENDENCIES = 'RECEIVE_DEPENDENCIES'
const RECEIVE_DEPENDENCIES_ERROR = 'RECEIVE_DEPENDENCIES_ERROR'
const SELECT_DEPENDENCY = 'SELECT_DEPENDENCY'
const EXPAND_COMPONENT = 'EXPAND_COMPONENT'
const EXPAND_COMPONENT_MINOR_VERSION = 'EXPAND_COMPONENT_MINOR_VERSION'
const EXPAND_VERSION = 'EXPAND_VERSION'
const CLOSE_COMPONENT = 'CLOSE_COMPONENT'
const EXPAND_GROUPED_COMPONENT = 'EXPAND_GROUPED_COMPONENT'
const CLOSE_GROUPED_COMPONENT = 'CLOSE_GROUPED_COMPONENT'
const REQUEST_GROUPED_COMPONENT_MINOR_VERSIONS = 'REQUEST_GROUPED_COMPONENT_MINOR_VERSIONS'
const RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS = 'RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS'
const RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS_ERROR = 'RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS_ERROR'
const EXPAND_GROUPED_COMPONENT_MINOR_VERSION = 'EXPAND_GROUPED_COMPONENT_MINOR_VERSION'
const CLOSE_GROUPED_COMPONENT_MINOR_VERSION = 'CLOSE_GROUPED_COMPONENT_MINOR_VERSION'
const REQUEST_GROUPED_COMPONENT_VERSIONS = 'REQUEST_GROUPED_COMPONENT_VERSIONS'
const RECEIVE_GROUPED_COMPONENT_VERSIONS = 'RECEIVE_GROUPED_COMPONENT_VERSIONS'
const SELECT_GROUPED_COMPONENT_VERSION = 'SELECT_GROUPED_COMPONENT_VERSION'
const REQUEST_ARTIFACTS = 'REQUEST_ARTIFACTS'
const RECEIVE_ARTIFACTS = 'RECEIVE_ARTIFACTS'
const REQUEST_DOCUMENT_ARTIFACT = 'REQUEST_DOCUMENT_ARTIFACT'
const RECEIVE_DOCUMENT_ARTIFACT = 'RECEIVE_DOCUMENT_ARTIFACT'
const ERROR_OCCURED = 'ERROR_OCCURED'
const HIDE_ERROR = 'HIDE_ERROR'
const TOGGLE_RC = 'TOGGLE_RC'
const TOGGLE_ADMIN_MODE = 'TOGGLE_ADMIN_MODE'
const HANDLE_COMPONENT_GROUP_TAB_CHANGE = 'HANDLE_COMPONENT_GROUP_TAB_CHANGE'
const DELETE_ARTIFACT = 'DELETE_ARTIFACT'
const SUCCESS_DELETE_ARTIFACT = 'SUCCESS_DELETE_ARTIFACT'
const SHOW_CONFIRMATION = 'SHOW_CONFIRMATION'
const HIDE_CONFIRMATION = 'HIDE_CONFIRMATION'
const REQUEST_SEARCH = 'REQUEST_SEARCH'
const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
const CHANGE_SEARCH_QUERY_VALID = 'CHANGE_SEARCH_QUERY_VALID'
const REQUEST_COMPONENT_MINOR_VERSIONS = 'REQUEST_COMPONENT_MINOR_VERSIONS'
const RECEIVE_COMPONENT_MINOR_VERSIONS = 'RECEIVE_COMPONENT_MINOR_VERSIONS'
const RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR = 'RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR'
const CLOSE_COMPONENT_MINOR_VERSION = 'CLOSE_COMPONENT_MINOR_VERSION'
const SELECT_VERSION = 'SELECT_VERSION'

export default {
    EXPAND_GROUPED_COMPONENT,
    CLOSE_GROUPED_COMPONENT,
    REQUEST_GROUPED_COMPONENT_MINOR_VERSIONS,
    RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS,
    RECEIVE_GROUPED_COMPONENT_MINOR_VERSIONS_ERROR,
    EXPAND_GROUPED_COMPONENT_MINOR_VERSION,
    CLOSE_GROUPED_COMPONENT_MINOR_VERSION,
    REQUEST_GROUPED_COMPONENT_VERSIONS,
    RECEIVE_GROUPED_COMPONENT_VERSIONS,
    SELECT_GROUPED_COMPONENT_VERSION,
    REQUEST_BUILD_INFO,
    RECEIVE_BUILD_INFO,
    REQUEST_LOGGED_USER,
    RECEIVE_LOGGED_USER,
    REQUEST_COMPONENTS,
    RECEIVE_COMPONENTS,
    REQUEST_VERSIONS,
    RECEIVE_VERSIONS,
    RECEIVE_VERSIONS_ERROR,
    CLOSE_VERSION,
    REQUEST_DEPENDENCIES,
    RECEIVE_DEPENDENCIES,
    RECEIVE_DEPENDENCIES_ERROR,
    SELECT_DEPENDENCY,
    EXPAND_COMPONENT,
    EXPAND_COMPONENT_MINOR_VERSION,
    EXPAND_VERSION,
    CLOSE_COMPONENT,
    REQUEST_ARTIFACTS,
    RECEIVE_ARTIFACTS,
    REQUEST_DOCUMENT_ARTIFACT,
    RECEIVE_DOCUMENT_ARTIFACT,
    ERROR_OCCURED,
    HIDE_ERROR,
    TOGGLE_RC,
    TOGGLE_ADMIN_MODE,
    HANDLE_COMPONENT_GROUP_TAB_CHANGE,
    DELETE_ARTIFACT,
    SUCCESS_DELETE_ARTIFACT,
    SHOW_CONFIRMATION,
    HIDE_CONFIRMATION,
    REQUEST_SEARCH,
    RECEIVE_SEARCH,
    CHANGE_SEARCH_QUERY_VALID,
    REQUEST_COMPONENT_MINOR_VERSIONS,
    RECEIVE_COMPONENT_MINOR_VERSIONS,
    RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR,
    CLOSE_COMPONENT_MINOR_VERSION,
    SELECT_VERSION
}
